// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr8qoRuDWmjG2A5eBhxULCdNjn0QRpcDY',
    appId: '1:974704287027:web:13965b7c51c6d461e3b246',
    messagingSenderId: '974704287027',
    projectId: 'my-app-b5ab9',
    authDomain: 'my-app-b5ab9.firebaseapp.com',
    storageBucket: 'my-app-b5ab9.firebasestorage.app',
    measurementId: 'G-8FTX5T31H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY292e9PCM1M9o4NDQc7ZPMRIiHo4Y29c',
    appId: '1:974704287027:android:f619d5926aee3757e3b246',
    messagingSenderId: '974704287027',
    projectId: 'my-app-b5ab9',
    storageBucket: 'my-app-b5ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6Wzmx2M4ugvs3N2n1oBfDMrxWc9_UXs',
    appId: '1:974704287027:ios:a9369a87bef193d2e3b246',
    messagingSenderId: '974704287027',
    projectId: 'my-app-b5ab9',
    storageBucket: 'my-app-b5ab9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6Wzmx2M4ugvs3N2n1oBfDMrxWc9_UXs',
    appId: '1:974704287027:ios:a9369a87bef193d2e3b246',
    messagingSenderId: '974704287027',
    projectId: 'my-app-b5ab9',
    storageBucket: 'my-app-b5ab9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr8qoRuDWmjG2A5eBhxULCdNjn0QRpcDY',
    appId: '1:974704287027:web:74c7b04acf1a13e9e3b246',
    messagingSenderId: '974704287027',
    projectId: 'my-app-b5ab9',
    authDomain: 'my-app-b5ab9.firebaseapp.com',
    storageBucket: 'my-app-b5ab9.firebasestorage.app',
    measurementId: 'G-11QEB4VLGP',
  );
}
